kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bonjour-artifacts
  namespace: demo-test
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem