apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: bonjour-tar-to-pvc
  namespace: demo-test
spec:
  params:
    - default: 'https://github.com/ktatro-rh/bonjour'
      name: repo_url
      type: string
    - default: master
      name: revision
      type: string
    - default: bonjour
      name: app_name
      type: string
    - default: artifacts
      name: pvc_subdir
      type: string
  tasks:
    - name: clone-tar-copy
      params:
        - name: repo_url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
        - name: app_name
          value: $(params.app_name)
        - name: pvc_subdir
          value: $(params.pvc_subdir)
        - name: version
          value: $(tasks.timestamp-task.results.current-date-unix-timestamp)
      runAfter:
        - timestamp-task
      taskSpec:
        metadata: {}
        params:
          - name: repo_url
            type: string
          - name: revision
            type: string
          - name: app_name
            type: string
          - name: pvc_subdir
            type: string
          - name: version
            type: string
        spec: null
        steps:
          - computeResources: {}
            image: 'docker.io/alpine/git:2.45.2'
            name: clone
            script: |
              set -eu
              echo "[clone] PWD=$(pwd)"
              git clone "$(params.repo_url)" repo
              cd repo
              git checkout "$(params.revision)"
              echo "[clone] done"
            workingDir: $(workspaces.scratch.path)
          - computeResources: {}
            image: 'alpine:3.20'
            name: make-tar
            script: |
              set -euo pipefail
              OUT="$(workspaces.scratch.path)/repo/$(params.app_name)-$(params.version).tar.gz"
              echo "[tar] PWD=$(pwd)"
              echo "[tar] creating $OUT (excluding .git)"
              tar -czf "$OUT" --exclude .git .
              echo "[tar] created:"
              ls -lh "$OUT"
            workingDir: $(workspaces.scratch.path)/repo
          - computeResources: {}
            image: registry.access.redhat.com/ubi9/ubi
            name: copy-to-pvc
            script: |
              set -euo pipefail
              SRC="$(workspaces.scratch.path)/repo/$(params.app_name)-$(params.version).tar.gz"
              DST_DIR="$(workspaces.outpvc.path)/$(params.pvc_subdir)"
              echo "[copy] SRC=$SRC"
              echo "[copy] DST_DIR=$DST_DIR"
              mkdir -p "$DST_DIR"
              cp "$SRC" "$DST_DIR/"
              echo "[copy] done:"
              ls -lh "$DST_DIR/$(params.app_name)-$(params.version).tar.gz"
              chmod 755 "$DST_DIR/$(params.app_name)-$(params.version).tar.gz"
            workingDir: $(workspaces.scratch.path)/repo
        workspaces:
          - name: scratch
          - name: outpvc
      workspaces:
        - name: scratch
          workspace: scratch
        - name: outpvc
          workspace: outpvc
    - name: timestamp-task
      taskRef:
        kind: Task
        name: timestamp-task
    - name: aap-launch-workflow
      params:
        - name: baseUrl
          value: "{{ aap_base_url }}"
        - name: workflowId
          value: '{{ workflow_id }}'
        - name: aapCredentialSecret
          value: aap-creds
        - name: deployment_version
          value: $(tasks.timestamp-task.results.current-date-unix-timestamp)
        - name: extra_vars_json
          value: |-
            {\"extra_vars\": {
            \"deployment_version\": \"$(tasks.timestamp-task.results.current-date-unix-timestamp)\", \"vm_project\": \"demo-test\", \"vm_name\": \"bonjour-vm\", \"deployment_name\": \"bonjour\", \"app_base_url\": \"{{ app_base_url }}\", \"artifact_base_url\": \"{{ artifact_base_url }}\"}}
      runAfter:
        - clone-tar-copy
      taskRef:
        kind: Task
        name: aap-launch-workflow
  workspaces:
    - name: scratch
    - name: outpvc
