apiVersion: v1
kind: Service
metadata:
  name: "{{ service_name }}"
  namespace: "{{ vm_project }}"
spec:
  selector:
    app: "{{ deployment_name }}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080