kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: "{{ route_name }}"
  namespace: "{{ vm_project }}"
spec:
  to:
    kind: Service
    name: "{{ service_name }}"
  tls: null
  port:
    targetPort: 8080