apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-hello-github
  namespace: demo-test
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations:
          pipeline.openshift.io/started-by: admin
        generateName: hello-pipeline-
        labels:
          tekton.dev/pipeline: hello-pipeline
        namespace: demo-test
      spec:
        params: []
        pipelineRef:
          name: hello-pipeline
        resources: []
        status: null
        workspaces:
          - name: workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: ocs-external-storagecluster-ceph-rbd
                volumeMode: Filesystem