apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-pipeline
  namespace: demo-test
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: '{{ github_url }}'
        - name: revision
          value: ''
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:1a50511583fc02a27012d17d942e247813404104ddd282d7e26f99765174392c
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: timestamp-task
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: timestamp-task
        apiVersion: tekton.dev/v1
    - name: create-tar-archive
      taskRef:
        kind: Task
        name: create-tar-archive
        apiVersion: tekton.dev/v1
      params:
        - name: archive-name
          value: output.tar
        - name: files-to-tar
          value: .
      runAfter:
        - timestamp-task
    - name: aap-launch-workflow-deploy-app
      params:
        - name: baseUrl
          value: "{{ aap_base_url }}"
        - name: workflowId
          value: '{{ workflow_id }}'
        - name: deployment_version
          value: $(tasks.timestamp-task.results.current-date-unix-timestamp)
        - name: aapCredentialSecret
          value: aap-creds
      runAfter:
        - create-tar-archive
      taskRef:
        kind: Task
        name: aap-launch-workflow
        apiVersion: tekton.dev/v1
  workspaces:
    - name: workspace
