apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: "{{ vm_name }}"
  namespace: "{{ vm_project }}"
spec:
  dataVolumeTemplates:
    - kind: DataVolume
      metadata:
        name: "{{ vm_name }}-{{deployment_version}}"
  template:
    spec:
      volumes:
        - dataVolume:
            name: "{{ vm_name }}-{{deployment_version}}"
          name: rootdisk